apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksk8sCluster1
  region: ap-southeast-2

nodeGroups:
  - name: nodegrpslave-1
    instanceType: t2.micro
    desiredCapacity: 1
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
      enableSsm: true
    labels:
      nodegroup: nodegrpslave-1

  - name: nodegrpslave-2
    instanceType: t2.xlarge
    desiredCapacity: 1
    ssh:
      allow: true
      enableSsm: true
    labels:
      nodegroup: nodegrpslave-2
