apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-webapp
  template:
    metadata:
      labels:
        app: node-webapp
    spec:
      containers:
      - name: node-webapp
        image: harinadh14/nodeapp:v2.0
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m

